/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnimobile_www_myjnidemo_helper_JniLib */

#ifndef _Included_com_jnimobile_www_myjnidemo_helper_JniLib
#define _Included_com_jnimobile_www_myjnidemo_helper_JniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnimobile_www_myjnidemo_helper_JniLib
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jnimobile_www_myjnidemo_helper_JniLib_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_jnimobile_www_myjnidemo_helper_JniLib
 * Method:    getBoolean
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jnimobile_www_myjnidemo_helper_JniLib_getBoolean
  (JNIEnv *, jobject);

/*
 * Class:     com_jnimobile_www_myjnidemo_helper_JniLib
 * Method:    show
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jnimobile_www_myjnidemo_helper_JniLib_show
  (JNIEnv *, jobject);

/*
 * Class:     com_jnimobile_www_myjnidemo_helper_JniLib
 * Method:    getAvg
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jnimobile_www_myjnidemo_helper_JniLib_getAvg
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
